{% set version = "1.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tdboost
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/TDboost_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/TDboost/TDboost_{{ version }}.tar.gz
  sha256: 4f08359d123a3be2fb12b1e05e6a5c0b6f0a597a31020d610375909bbd79a5d3

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-lattice
  run:
    - r-base
    - r-lattice

test:
  commands:
    - $R -e "library('TDboost')"           # [not win]
    - "\"%R%\" -e \"library('TDboost')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=TDboost
  license: GPL-3.0-only
  summary: 'A boosted Tweedie compound Poisson model using the gradient boosting. It is capable of fitting a flexible nonlinear Tweedie compound Poisson model (or a gamma model) and capturing interactions among predictors. '
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - xhochy

# Package: TDboost
# Title: A Boosted Tweedie Compound Poisson Model
# Version: 1.2
# Date: 2016-03-29
# Author: Yi Yang <yi.yang6@mcgill.ca>, Wei Qian <wxqsma@rit.edu>, Hui Zou <hzou@stat.umn.edu>
# Maintainer: Yi Yang <yi.yang6@mcgill.ca>
# Depends: R (>= 2.12.0), lattice
# Description: A boosted Tweedie compound Poisson model using the gradient boosting. It is capable of fitting a flexible nonlinear Tweedie compound Poisson model (or a gamma model) and capturing interactions among predictors.
# LazyData: yes
# License: GPL-3
# Packaged: 2016-03-30 02:49:54 UTC; yiyang
# NeedsCompilation: yes
# Date/Publication: 2016-03-30 08:14:25
# Repository: CRAN
