travis:
  secure:
    BINSTAR_TOKEN: FOEAQ6ueG7qn4zZG4Ca5qe+yILf5P7/a9NlEhPJ4S5JHK4XzcmFCHPBAL2NLl0cdEaiXREABeXCfNsEjf8R6BWcq6GQwLZHVs/pMjkDO8x5Pv46Yr/lHeERLawC0FGo8nSVMRLx/+kOXUPbdC/LdaZ5u1a9WQh0LqBfWrG6YvVIQysbfX2C3/XIESBiauMfiNrbThMwBRaqoTF3yEKISqyZ8MOs+9DJJn3q3u13yzwgo2tFUMJ3j883mtlZdtPaZzXW5jPtRHyACt9M9msg/H0F9f/C7R3pAWIMYTD1IOQjanfwZP6Rx7SMasEEdXgFwTnznJTzd+EpKYoJ8EIV4RjFIK4HWdElejcu0loYPeAPJQEt1oBvn0H9+y8PdO8oOSHvdZRc/QaYfz17WOmtGFlCbeLPgouIE+xxv8BpGu8pIIsd+/uqaruaWYbTGekMe8BFxEGIuCkTugUzysXW3+EmDhfJaWTNNA/hVc/7/FjRYmK665oN6tHqdXgTaNdWmnwODyBbtBxgOe8O7ndzgozDGwwEQ9D0tzhySgO5b6cA2wGFBrChDYD7N7amwGXyhzX4rR3oeidaieODpsDxNGPrEuMFca/9VCjLhmpfvyAe4YbnbXua+DrcIpAfBUkGR83ScQvnEd7SgpvZhOCIm01hU6lxvGnUjZ5g5E9PhwV4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
