appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: orRmVDOrgwXekhNGdSkjSp2XUFLdwnxM+5HWpol1a49wSuDiO9nqgShD3WZHRVn8ofDPU3VR0IKZtJb0l4vAQGMBTB80FEU854J3q/EioXpILM3qYj2iBJFHOYtbllMWn+IwlcYjr+nsOlyPID8OUJbaqVtBBDklnDZVe4E2y9K074Dp0wHiOPeBDWje/LEncYJvVyM68/cXCqgtPstQGL/qehq6SemPElsWyvYDs1NLsnFpHWpqbH5V1rZb6Tc5SEfFMor7uc2N/sGMQJdSQpnQ8dc610nt14M/fkRdk0g7e8MwX0v7uiwqpl8mrcvwQAJMXO3/oTFlE98wo8Ygv5B8ihNo9eJ+YcXikzvTkcnGDKLUX+wZWA/Gjz21cmZ38pCMUl6bYtxLD9xWn8HmzKKqKI0W5P2+tOElJMl4MrvYqg6gTTQL891sKOR2t6mnS7wAvXiRdbJj5EOGMJOUWgnmSrZiJDvJBe23qRsplkLlWCBgWO+eou5j9toypA4XYQ6MD20EJEHMMwA9Le/4GV01oxWOsDexu4hAsYIsI7BA3bg6c0OJMr4xyIVMnE/Dja2oH14hmUyDptAFty5IwA8WgQWweKAfzvQYJn1Yb4/ZUfKuz8zQqXGCBlTXCQCaPj0x2RCVc8PIrxVy3JNp5nDAtn91qr5Eavr4ioQ/FxY=
conda_forge_output_validation: false
